### ISSUE TITLE
CSS Selectors

### ISSUE THREAD

**Issue by voidove** [voidove/jug-jug#21]
## CSS Selectors

[W3 Selectors](http://www.w3.org/TR/selectors/#selectors)
#### 1.1 通用元素选择器(Universal Selector)

``` css
* {
   color: green;
   font-size: 20px;
   line-height: 25px;
}
```
#### 1.2 标签选择器(Element Type Selector)

``` css
ul {
   list-style: none;
   border: solid 1px #ccc;
}
```
#### 1.3 ID选择器(ID Selector)

``` css
#container {
   width: 960px;
   margin: 0 auto;
}
```
#### 1.4 Class选择器(Class Selector)

``` css
.box {
   padding: 20px;
   margin: 10px;
   width: 240px;
}
```
#### 2.1 群组选择器

多个选择符应用同样的样式，各选择符之间用`,` 分隔。

``` css
h1,
h2,
h3 {
  font-weight: normal;
  line-height: 1.2;
}
```
#### 2.2 后代选择器(Descendant Selector)

`A E` 任何是元素A的后代元素E (后代节点指A的子节点，子节点的子节点，以此类推)，A和E之间用空格分隔。

``` css
li a {
  text-decoration: none;
}
```
#### 2.3 子选择器(Child Selector)

`A > E` 匹配所有A元素的子元素E

``` css
#container > .box {
   float: left;
   padding-bottom: 15px;
}
```
#### 2.4 毗邻选择器(Adjacent Selector)

``` html
<h2>Title</h2>
<p>Paragraph example.</p>
<p>Paragraph example.</p>
<p>Paragraph example.</p>
```

`B + E` 匹配所有紧随B元素之后的同级元素E。只匹配第一个p元素。

``` css
h2 + p {
   color: blue;
}
```

`B ~ E` 匹配所有B元素之后的同级元素E。匹配所有p元素。

``` css
h2 ~ p {
   color: blue;
}
```
#### 3.1 E[att]

匹配所有具有att属性的E元素，不考虑它的值。（注意：E在此处可以省略，比如"[cheacked]"。以下同。）

``` css
input[type] {
   background-color: #444;
   width: 200px;
}
```
#### 3.2 E[att=val]

匹配所有att属性等于"val"的E元素

``` css
input[type="text"] {
   background-color: #444;
   width: 200px;
}
```
#### 4.1 X:hover

``` css
a:hover {
   color: red;
}
```
#### 4.2 X:not(selector)

``` css
div:not(#container) {
   color: blue;
}

*:not(p) {
  color: green;
}
```
#### 4.3 X:first-child

``` css
ul li:first-child {
   border-top: none;
}
```
#### 4.4 X:last-child

``` css
ul > li:last-child {
   color: green;
}
```
#70
#### 5.1 css匹配规则

浏览器在解析css选择器时，是<b>自右向左</b>匹配的。

``` css
#home a {
  color: blue;
}
```

上面这个例子，我们所期望的匹配顺序是：找到id为home的元素，然后从它的子元素中找出所有a标签，并应用样式。然而，由于浏览器是从右向左进行匹配，所以这一过程实际上是这样的：找到所有a标签，然后逐一寻找存在id为home的父节点的标签，直到文档全部扫描完。
#### 5.2 css匹配规则

对于一个给定的元素，需要匹配的规则越少，样式的解析就会越快。
#### Don’t qualify ID rules with tag names or classes

If a rule has an ID selector as its key selector, don’t add the tag name to the rule. Since IDs are unique, adding a tag name would slow down the matching process needlessly.

``` css
/* Not recommended */
ul#example {}

/* Recommended */
#example {}
```
#### Don’t qualify class rules with tag names

按照惯例，你可以将标签名写到 class 名里。当然，这会有损灵活性；如果设计更改，标签变动，class 名也要跟着变动。(最好的办法是选择严格语义化的名字，毕竟分离样式表的一个目标就是为了灵活性。)

``` css
/* BAD */
treecell.indented {…}

/* GOOD */
.treecell-indented {…}

/* BEST */
.hierarchy-deep {…}
```
#### Use the most specific category possible

The single biggest cause of slowdown is too many rules in the tag category. 
#### Avoid the descendant selector

The descendant selector is the most expensive selector in CSS.
#### Tag category rules should never contain a child selector

Avoid using the child selector with tag category rules.

``` css
/* Not recommended */
treehead > treerow > treecell {…}

/* Recommended */
.treecell-header {…}
```
#### Rely on inheritance

Learn which properties inherit, and allow them to do so! 

``` css
/* Not recommended */
#bookmarkMenuItem > .menu-left { list-style-image: url(blah) }

/* Recommended */
#bookmarkMenuItem { list-style-image: url(blah) }
```
### 参考：

<a href="http://code.tutsplus.com/tutorials/the-30-css-selectors-you-must-memorize--net-16048" target="_blank">The 30 CSS Selectors you Must Memorize</a>
<a href="http://www.sitepoint.com/web-foundations/css-selectors/" target="_blank">CSS Selectors</a>
<a href="http://www.ruanyifeng.com/blog/2009/03/css_selectors.html" target="_blank">CSS选择器笔记</a>
<a href="https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Getting_started/Selectors" target="_blank">MDN Selectors</a>
<a href="https://developer.mozilla.org/zh-CN/docs/Web/CSS/Writing_Efficient_CSS" target="_blank">MDN Writing efficient CSS</a>
[CSS 选择器参考手册](http://www.w3school.com.cn/cssref/css_selectors.asp)
