### ISSUE TITLE
CSS布局 -- BFC （一）

### ISSUE THREAD

**Issue by voidove** [voidove/jug-jug#25]
### 1 BFC是什么

BFC(Block Formatting Context)，简单讲，它提供了一个独立布局的环境，HTML元素在这个环境中按照一定规则进行布局。

<a href="http://www.w3.org/TR/CSS21/visuren.html#block-formatting" target="_blank">W3C CSS 2.1</a>标准中这样描述：

> Floats, absolutely positioned elements, block containers (such as inline-blocks, table-cells, and table-captions) that are not block boxes, and block boxes with 'overflow' other than 'visible' (except when that value has been propagated to the viewport) establish new block formatting contexts for their contents.
> 
> In a block formatting context, boxes are laid out one after the other, vertically, beginning at the top of a containing block. The vertical distance between two sibling boxes is determined by the 'margin' properties. Vertical margins between adjacent block-level boxes in a block formatting context collapse.
> 
> In a block formatting context, each box's left outer edge touches the left edge of the containing block (for right-to-left formatting, right edges touch). This is true even in the presence of floats (although a box's line boxes may shrink due to the floats), unless the box establishes a new block formatting context (in which case the box itself may become narrower due to the floats).

非块级盒子的浮动元素、绝对定位元素及块级容器(比如inline-blocks，table-cells和table-captions)，以及overflow属性是visible之外任意值的块级盒子，都会创建一个BFC。

`Document`显示HTML元素的方式和BFC的定义很像，其实我们可以认为`Document`就是最大的一个拥有BFC的元素了。

即当元素的CSS属性设置了下列之一时，就可**创建一个BFC**：
- `float`: left | right
- `position`: absolute | fixed
- `display`: table-cell | table-caption | inline-block
- `overflow`: hidden | scroll | auto
- flex boxes (`display: flex | inline-flex`)

**BFC布局规则**：
1.  在同一个BFC内，垂直方向上`Box`会一个挨着一个的排；
2.  `Box`垂直方向的距离由margin决定。属于同一个BFC的两个相邻`Box`的margin会发生重叠；
3.  每个元素的margin box的左边， 与包含块border box的左边相接触(对于从左往右的格式化，否则相反)。即使存在浮动也是如此；
4.  `BFC`的区域不会与`float Box`重叠；**????**
5.  `BFC`就是页面上的一个隔离的独立容器，容器里面的子元素不会影响到外面的元素，反之也如此；
6.  计算`BFC`的高度时，浮动元素也参与计算；
#### 2.1 自适应两栏布局

html

``` html
<div class="item">
  <div class="pic">photo</div>
  <p class="cont">
    莫听穿林打叶声，何妨吟啸且徐行。
    竹杖芒鞋轻胜马，谁怕？一蓑烟雨任平生。 
    料峭春风吹酒醒，微冷，山头斜照却相迎。
    回首向来萧瑟处，归去，也无风雨也无晴。
  </p>
</div>
```

css

``` css
.item {
  width: 300px;
  border: 1px solid #b2d1a3;
  background-color: #e5ebe4;
}

.pic {
  width: 80px;
  height: 80px;
  margin: 10px;
  color: #fff;
  background-color: #acdae5;
}

.cont {
  margin: 10px;
  color: #37a;
}
```

效果如下：
![test](https://cloud.githubusercontent.com/assets/5563419/4116184/0b192a76-3282-11e4-867f-44a955fa72d3.png)

这时，如果要将文字部分放到图片的右侧，很多人都会想到给`.pic`使用`float`：

``` css
.pic {
  float: left;
}
```

效果如下：
![test2](https://cloud.githubusercontent.com/assets/5563419/4116216/91d81752-3282-11e4-89cd-eddcb25dc010.png)

右侧内容并没有如我们所预料的，规整的排在右侧，而是将左侧图片包围起来。根据BFC布局规则第四条：

> `BFC`的区域不会与`float Box`重叠；

因此，为右侧内容设置`overflow: hidden`属性，使它形成一个新的BFC。

``` css
.cont {
  overflow: hidden;
}
```

效果：
![test3](https://cloud.githubusercontent.com/assets/5563419/4116522/ff0c45ca-3285-11e4-8105-af30d090b0bf.png)
#### 2.3 防止垂直margin重叠

未完，见下篇：#26
