### ISSUE TITLE
CSS布局 -- BFC （二）

### ISSUE THREAD

**Issue by voidove** [voidove/jug-jug#26]
接上篇，CSS布局 -- BFC （一）：#25
#### 2.2 清除内部浮动

html

``` html
<div class="par">
  <div class="child"></div>
  <div class="child"></div>
</div>
```

css

``` css
.par {
  border: 5px solid #fcc;
  width: 300px;
}

.child {
  border: 5px solid #f66;
  width:100px;
  height: 100px;
  float: left;
}
```

效果如下：
![test](https://cloud.githubusercontent.com/assets/5563419/4117110/62cd779e-328d-11e4-9a3c-be382d899cf8.png)
现在，我们想让父元素`par`的高度自适应子元素的高度，根据BFC布局规则第六条：

> 计算BFC的高度时，浮动元素也参与计算

因此，为父元素`par`设置`overflow: hidden`属性，使它形成一个新的BFC。那么父元素在计算高度时，内部的浮动元素也会参与计算。

``` css
.par {
  overflow: hidden;
}
```

效果如下：
![test2](https://cloud.githubusercontent.com/assets/5563419/4116934/1dd2ca7e-328b-11e4-9f47-34fc3a1b7c34.png)
#### 2.3 防止垂直margin重叠

html

``` html
<p>Haha</p>
<p>Hehe</p>
```

css

``` css
p {
  color: #f55;
  background: #fcc;
  width: 200px;
  line-height: 100px;
  text-align:center;
  margin: 10px;
}
```

效果如下：
![test3](https://cloud.githubusercontent.com/assets/5563419/4117111/67b6b40a-328d-11e4-9445-e1e90a8b6709.png)
两个`p`元素的垂直间距为10px，发生了margin重叠。
见BFC布局规则第二条：

> `Box`垂直方向的距离由margin决定。属于同一个BFC的两个相邻`Box`的margin会发生重叠；

我们可以在任意一个`p`元素外面包裹一层容器，并触发该容器生成一个BFC。那么两个`P`便不属于同一个BFC，就不会发生margin重叠了。

html

``` html
<p>Haha</p>

<div class="wrap">
  <p>Hehe</p>
</div>
```

css

``` css
.wrap {
  overflow: hidden;
}

p {
  color: #f55;
  background: #fcc;
  width: 200px;
  line-height: 100px;
  text-align:center;
  margin: 10px;
}
```

效果如下：
![test4](https://cloud.githubusercontent.com/assets/5563419/4117107/5ddb3974-328d-11e4-9aae-70a758855cd3.png)
### 总结

其实以上的几个例子都体现了BFC布局规则第五条：

> `BFC`就是页面上的一个隔离的独立容器，容器里面的子元素不会影响到外面的元素，反之也如此。

因为BFC内部的元素和外部的元素绝对不会相互影响，因此， 当BFC外部存在浮动时，它不应该影响BFC内部Box的布局，BFC会通过变窄，而不与浮动有重叠。同样的，当BFC内部有浮动时，为了不影响外部元素的布局，BFC计算高度时会包括浮动的高度。避免margin重叠也是这样的一个道理。
### 参考

<a href="http://www.aliued.cn/2012/12/31/css%E5%B8%83%E5%B1%80%E4%B8%AD%E4%B8%80%E4%B8%AA%E7%AE%80%E5%8D%95%E7%9A%84%E5%BA%94%E7%94%A8bfc%E7%9A%84%E4%BE%8B%E5%AD%90.html" target="_blank">CSS布局中一个简单的应用BFC的例子</a>
<a href="http://f2e-js.com/?p=2599" target="_blank">BFC 神奇背后的原理</a>
<a href="http://blog.csdn.net/borishuai/article/details/8127758" target="_blank">CSS BFC和IE Haslayout介绍</a>
