### ISSUE TITLE
Sass 入门

### ISSUE THREAD

**Issue by voidove** [voidove/jug-jug#63]
## What is SASS?
Sass (Syntactically Awesome StyleSheets)

平时常用`CSS`开发网页样式， 但它不是一种编程语言，基本上是设计师的工具。

一旦为`CSS`加入编程因素，就有了`CSS 预处理器`。它的基本思想是，用一种专门的编程语言，进行网页样式设计，然后再编译成正常的`CSS文`件。

### 变量（Variables）
`SASS`允许使用变量，所有变量以`$`开头。
#### 普通变量
```sass
$font-stack: Helvetica, sans-serif;
$primary-color: #333;

body {
  font: 100% $font-stack;
  color: $primary-color;
}
```
编译后：
```css
body {
  font: 100% Helvetica, sans-serif;
  color: #333;
}
```

#### 默认变量

`sass`的默认变量，需要在值后面加上`!default`。
```sass
$baseLineHeight: 1.5 !default;

body {
    line-height: $baseLineHeight; 
}
```
编译后：
```css
body {
    line-height: 1.5;
}
```
`sass`的默认变量一般是用来设置默认值，然后根据需求来覆盖，覆盖的方式也很简单，只需要在默认变量前重新声明下变量即可：
```sass
$baseLineHeight: 2;
$baseLineHeight: 1.5 !default;

body {
    line-height: $baseLineHeight; 
}

```
编译后：
```css
body {
    line-height: 2;
}
```
### 嵌套（Nesting）
* 选择器嵌套
* 属性嵌套

#### 选择器嵌套

选择器嵌套，指的是在一个选择器中嵌套另一个选择器来实现继承，从而增强了`sass`文件的结构性和可读性。
在选择器嵌套中，可以使用`&`引用父元素选择器，如下`a:hover`。
```sass
#top_nav {
  line-height: 40px;
  text-transform: capitalize;
  background-color: #333;
  li {
    float:left;
  }
  a {
    display: block;
    padding: 0 10px;
    color: #fff;

    &:hover {
      color: #ddd;
    }
  }
}

```
编译后：
```sass
#top_nav {
  line-height: 40px;
  text-transform: capitalize;
  background-color: #333;
}  
#top_nav li {
  float:left;
}
#top_nav a {
  display: block;
  padding: 0 10px;
  color: #fff;
}
#top_nav a:hover {
  color: #ddd;
}
```
#### 属性嵌套
```sass
.funky {
  font: {
    family: fantasy;
    size: 30em;
    weight: bold;
  }
}
```
编译后：
```css
.funky {
  font-family: fantasy;
  font-size: 30em;
  font-weight: bold; 
}
```
### Mixins
使用`@mixin`命令，定义一个代码块。可以传递参数，参数名以`$`符号开始，多个参数以逗号分开，也可以给参数设置默认值。声明的`@mixin`通过`@include`来调用。
* Demo-1
```sass
@mixin border-radius($radius) {
  -webkit-border-radius: $radius;
     -moz-border-radius: $radius;
      -ms-border-radius: $radius;
          border-radius: $radius;
}

.box { 
  @include border-radius(10px);
 }
```
编译后：
```css
.box {
  -webkit-border-radius: 10px;
  -moz-border-radius: 10px;
  -ms-border-radius: 10px;
  border-radius: 10px;
}
```
* Demo-2
```sass
@mixin left($value: 10px) {
  float: left;
  margin-right: $value;
}

div {
  @include left(20px);
}
```
编译后：
```css
div {
  float: left;
  margin-right: 20px;
}
```
### 继承（Extend/Inheritance）
`sass`中，允许一个选择器继承另一个选择器的所有样式，并联合声明。要使用关键词`@extend`，后面紧跟需要继承的选择器。
```sass
.message {
  border: 1px solid #ccc;
  padding: 10px;
  color: #333;
}

.success {
  @extend .message;
  border-color: green;
}

.error {
  @extend .message;
  border-color: red;
}
```
编译后：
```css
.message,
.success,
.error {
  border: 1px solid #cccccc;
  padding: 10px;
  color: #333;
}

.success {
  border-color: green;
}

.error {
  border-color: red;
}
```
### 导入（import）
`sass`的导入(`@import`)规则和`CSS`的有所不同。编译时会将`@import`的`scss`文件合并进来只生成一个`CSS`文件。
>
如果在`sass`文件中导入`css`文件如`@import 'reset.css'`，效果跟普通CSS导入样式文件一样，导入的`css`文件不会合并到编译后的文件中，而是以`@import`方式存在。

所有的`sass`导入文件都可以忽略后缀名`.scss`。一般来说，基础文件命名以`_`开头，如`_reset.scss`。这种文件在导入的时候可以不写下划线，可写成`@import "reset"`。

_reset.sass
```sass
// _reset.scss

html,
body,
ul,
ol {
   margin: 0;
  padding: 0;
}
```
base.sass
```sass
@import 'reset';

body {
  font: 100% Helvetica, sans-serif;
  background-color: #efefef;
}
```
编译后的`base`文件：
```sass
html, body, ul, ol {
  margin: 0;
  padding: 0;
}

body {
  font: 100% Helvetica, sans-serif;
  background-color: #efefef;
}
```

### 计算（Operators）
`sass`具有运算的特性，可以对数值型的`Value`(如：数字、颜色、变量等)进行加减乘除四则运算。
> 注意：运算符前后要留一个空格，不然会出错。

```sass
.container { width: 100%; }

article[role="main"] {
  float: left;
  width: 600px / 960px * 100%;
}

aside[role="complimentary"] {
  float: right;
  width: 300px / 960px * 100%;
}
```
编译后：
```css
.container {
  width: 100%;
}

article[role="main"] {
  float: left;
  width: 62.5%;
}

aside[role="complimentary"] {
  float: right;
  width: 31.25%;
}
```

### 注释（Comments）
`SASS`共有两种注释风格。
* 标准的CSS注释 `/* comment */` ，会保留到编译后的文件。
* 单行注释 `// comment`，只保留在`SASS`源文件中，编译后被省略。
```sass
/* This comment is
 * several lines long.
 * since it uses the CSS comment syntax,
 * it will appear in the CSS output.
 */
body {
  color: black; 
}

// These comments are only one line long each.
// They won't appear in the CSS output,
// since they use the single-line comment syntax.
a {
  color: green;
}
```
编译后：
```css
/* This comment is
 * several lines long.
 * since it uses the CSS comment syntax,
 * it will appear in the CSS output.
 */
body {
  color: black; 
}

a {
  color: green; 
}
```

在`/*`后面加一个感叹号，表示这是"重要注释"。即使是压缩模式编译，也会保留这行注释，通常可以用于声明版权信息。
```sass
/*! 
 重要注释！
*/
```

## 参考
[SASS用法指南](http://www.ruanyifeng.com/blog/2012/06/sass.html)
[Sass Basics](http://sass-lang.com/guide)
[sass语法](http://www.w3cplus.com/sassguide/syntax.html)
