### ISSUE TITLE
CSS 伪类

### ISSUE THREAD

**Issue by voidove** [voidove/jug-jug#70]
## CSS Pseudo class
> CSS 伪类用于向某些选择器添加特殊效果。

```css
selector:pseudo-class {
  property: value;
}
```
### 1 动态伪类
动态伪类，因为这些伪类并不存在于HTML中，而只有当用户和网站交互的时候才能体现出来，包含两种：
* 链接中常见的锚点伪类，如`:link`, `:visited`;
* 用户行为伪类，如`:hover`, `:active` 和 `:focus`;

平时最常用超链接 `<a>` 的伪类，但是 `<a>` 必须要有 `href` 属性。
```css
a:link {color: #FF0000}		/* 未被访问状态 */
a:visited {color: #00FF00}	/* 已被访问状态 */
a:hover {color: #FF00FF}	/* 鼠标悬停状态 */
a:active {color: #0000FF}	/* 活动状态 */
```
**NOTE**:
> 1. `a:hover` 必须被置于 `a:link` 和 `a:visited` 之后，才是有效的；
2. `a:active` 必须被置于 `a:hover` 之后，才是有效的；
3. 伪类名称对大小写不敏感；
4. 快速记忆：LOVE' (**LV**) and 'HATE' (**HA**).

对于 `<a>`, 鼠标悬停状态可以用 `hover`，如果用键盘访问的话，则该用 `focus`。
```css
input:focus {}
```
### 2 UI元素状态伪类
可以根据元素状态来设定样式，通常是表单元素
```css
input:enabled {}
input:disabled {}
input[type=radio]:checked {}
```
### 3 结构伪类
根据元素在文档中的位置来选择。
```css
E:root	                  /* an E element, root of the document */
E:nth-child(n)	          /* an E element, the n-th child of its parent*/
E:nth-last-child(n)	an E element, the n-th child of its parent, counting from the last one
E:nth-of-type(n)	an E element, the n-th sibling of its type
E:nth-last-of-type(n)	an E element, the n-th sibling of its type, counting from the last one
E:first-child	an E element, first child of its parent
E:last-child	an E element, last child of its parent
E:first-of-type	an E element, first sibling of its type
E:last-of-type	an E element, last sibling of its type
E:only-child	an E element, only child of its parent
E:only-of-type	an E element, only sibling of its type
E:empty	an E element that has no children (including text nodes)
```
